source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'StormLab' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'
end
